version: '3.9'

services:
  ctfd:
    image: ctfd/ctfd:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      - REDIS_URL=redis://cache:6379
      - SECRET_KEY=${CTFD_SECRET_KEY}
    volumes:
      - ctfd_uploads:/var/uploads
      - ctfd_logs:/var/log/CTFd
    depends_on:
      - db
      - cache

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    volumes:
      - ctfd_db_data:/var/lib/mysql

  cache:
    image: redis:7-alpine
    restart: always
    volumes:
      - ctfd_redis_data:/data

volumes:
  ctfd_db_data:
  ctfd_redis_data:
  ctfd_uploads:
  ctfd_logs: